# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: python:3.5.1
image:
    name: basepair/webapp
    username: basepair
    password: MMV{3Z/m6*%AsG79
    email: info@basepairtech.com

options:
  max-time: 15

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - pip install -U tox
          # - pip --version
          # - tox --version

          - pwd
          - whoami

          # db setup
          - /start_postgres.sh
          - su postgres -c "createuser -d bpdjango"
          - su postgres -c "createdb --owner bpdjango bpapp"
          - psql bpapp bpdjango -c "ALTER USER bpdjango WITH ENCRYPTED PASSWORD 'yW4AFREYl)Jp'"

          - yum install -y https://centos7.iuscommunity.org/ius-release.rpm 
          - yum install -y python36u python36u-devel python36u-pip
          - virtualenv -p /usr/bin/python3.6 /root/.virtualenvs/webapp
          - source /root/.virtualenvs/webapp/bin/activate
          - python --version

          # clone webapp repo
          - hg clone https://$REPO_USER:$REPO_KEY@bitbucket.org/basepair/webapp /webapp

          # # temporaray until we update default with most recent changes
          # - cd /webapp
          # - hg up bug_fixes
          # - cd $BITBUCKET_CLONE_DIR

          # set up webapp stuff
          - pip install -r /webapp/requirements.txt
          - mkdir -p /webapp/app/build/static
          - /webapp/www/manage.py collectstatic --noinput
          - /webapp/www/manage.py migrate
          
          - /webapp/bin/model-ops.py create-user --userid 16 --username utk --password hadfdfa --email=amit+logs@basepairtech.com
          - psql bpapp bpdjango -c "UPDATE bpapp_bpuser SET is_superuser = true WHERE id = 16;"
          
          - /webapp/www/manage.py runserver 80 --insecure &
          - sleep 5  # give a few seconds for server to start
          
          - /webapp/bin/model-ops.py create-user --userid 17 --username micT --password basepair --email=michael+test@basepairtech.com
          - /webapp/bin/model-ops.py create-user --userid 18 --username alice --password basepair --email=michael+alice@basepairtech.com
          - /webapp/bin/model-ops.py create-user --userid 19 --username bob --password basepair --email=michael+bob@basepairtech.com
          - /webapp/bin/model-ops.py create-user --userid 20 --username claire --password basepair --email=michael+claire@basepairtech.com
          - /webapp/bin/load-data.py -d -r

          - /webapp/bin/model-ops.py get-config -u 16 > /root/bp.super.config.json
          - export BP_SUPER_API_CONFIG=/root/bp.super.config.json
          - /webapp/bin/model-ops.py get-config -u 17 > /root/bp.config.json
          - export BP_API_CONFIG=/root/bp.config.json
          - /webapp/bin/model-ops.py get-config -u 18 > /root/bp.alice.config.json
          - export BP_ALICE_API_CONFIG=/root/bp.alice.config.json
          - /webapp/bin/model-ops.py get-config -u 19 > /root/bp.bob.config.json
          - export BP_BOB_API_CONFIG=/root/bp.bob.config.json
          - /webapp/bin/model-ops.py get-config -u 20 > /root/bp.claire.config.json
          - export BP_CLAIRE_API_CONFIG=/root/bp.claire.config.json

          # run tests
          - cd tests
          - nose2 test_samples test_genes
